### ISSUE TITLE
Questions about Async messaging

### ISSUE THREAD

**Issue by ElVasquito** [shurillu/CTBot#34] opened 2019-11-05 05:11 UTC
Hi Stefano!

Very good news, I just saw the new version. Pretty neat about the complete contact request :)
Now some questions about removing (or at least attenuating) the ~1.5" freeze in the loop while checking for new messages...
Checking through ESPAsyncTcp would be an option to improve this?
Or maybe doing getNewMessage() inside a co-routine from a multitasking library like https://github.com/bxparks/AceRoutine?
Would that work? I haven't tried it yet because I think everything will crash, hahaha
Thank you!

**Comment by shurillu** [comment] 2019-11-05 09:27
Hola Marton, 
   ¿que tal? Thanks for trying the new version: let me know if you encounter issues or if you have ideas for improvements!
Speaking about the possibility to send/receive asynchronous messages, it's an upgrade that I have in mind, but I guess it is a bit weighty so I'm waiting to have some time to dedicate.
ESPAsyncTcp could be a good choice: I have to check if support the fingerprint because from the 2.5.0 the ESP8266 Core need it for HTTPS connections.

¡Hasta pronto!

Stefano

**Comment by shurillu** [comment] 2019-11-05 09:30
Duplicate of #15

**Closed by shurillu** 2019-11-05 09:30 UTC
