### ISSUE TITLE
[Help] Understand if message comes from inline keyboard

### ISSUE THREAD

**Issue by leobel96** [shurillu/CTBot#9] opened 2018-09-25 20:12 UTC
Hello, I know it isn't a real issue but it is partially related to this library and, so, I ask it here. I have made an Inline Keyboard for my bot (I really like your library, great work) and I know if a message comes from a button using messageType. The menu I've made is multipage and after that you have pressed a sequence of buttons, my bot asks you a text value that you have to write using the classic keyboard; is there a way to recognise a message which has been written in this way? I don't know if I was clear. Thank you!

**Comment by shurillu** [comment] 2018-09-26 06:20
Hello Leonardo,

 

This is not a issue related to the library implementation but it is related to the implementation/design of the your app.

 

So I should close this issue but today I'm in a good mood :-)

 

Just to better understand your problem, let me use this example.

 

A supermarket implement a bot to make orders using the inline keyboard. The first “layer” of menu ask to the consumer if he/she want to buy vegetables or meat

 

What do you want to buy?

[Vegetables] [Meat]

 

I choose “Meat”. Then the bot show the kind of meat I want to buy, for example:

 

What kind of meat? 

                [Pork] [Beef] [Chicken]

 

Finally the bot ask me how much meat, in grams, and I have to insert the weight using the traditional keyboard.

 

So the problem is identify when a text digited with the keyboard is "the amount of meat ordered" rather than "the amount of vegetables" or a generic text... Is it correct?

 

Stefano

**Comment by leobel96** [comment] 2018-09-26 07:40
Yes, It's correct!

**Comment by shurillu** [comment] 2018-09-26 11:45
Good. So, in the scenario explained above, a possibly solution could be use a variable that memorize a code that identify what kind of message will be input by the user.

 

Using the example above, we define three kind of messages:

 

   #define GENERAL_MESSAGE 0

   #define MEAT_WEIGHT_MESSAGE 1

   #define VEGETABLE_WEIGHT_MESSAGE 2

 

Furthermore, we declare a global variable that will store the message type:

 

   uint8_t messageType

 

In the initialization block (void init()) we initialize the variable with the value GENERAL_MESSAGE because we are not asking nothing regarding the order (meat/vegetables)

 

When the user arrive at the point that is asked to input the weight of the meat:

 

   1) the user press the [Meat] button

   2) the user press the [Chicken] button

 

the messageType variable should assume the value MEAT_WEIGHT_MESSAGE.

 

The function that handle incoming text messages now can discriminate between every kind of messages simply checking the "messageType" variable:

 

switch (messageType) {

   case GENERAL_MESSAGE:

      //handle a general message

   break;

   case MEAT_WEIGHT_MESSAGE:

      // handle meat order

   break;

   ...

   default:

      // other...

   break;

}

 

Obviously, this is a very simple example and do not cover/memorize the kind of meat ordered (for example) and does not handle the message status change (i.e. at the end of the meat order, you have to set the messageType to GENERAL_MESSAGE because the order is complete and further messages does not belongs anymore to the previous meat order).

 

Can we close it?

 

Good luck!

 

Stefano

 

 

 

Da: Leonardo Bellettini [mailto:notifications@github.com] 
Inviato: mercoledì 26 settembre 2018 09:40
A: shurillu/CTBot <CTBot@noreply.github.com>
Cc: Stefano Ledda <shurillu@tiscalinet.it>; Comment <comment@noreply.github.com>
Oggetto: Re: [shurillu/CTBot] [Help] Understand if message comes from inline keyboard (#9)

 

Yes, It's correct!

**Comment by shurillu** [comment] 2018-09-26 13:37
Mmmm, the problem is not so simply. 
For every customer, you have to know the kind of food and the quantity/weight desired.
So you can define every possible food like that:

   #define NO_FOOD 0
   #define MEAT_PORK 1
   #define MEAT_BEEF 2
   #define MEAT_CHICKEN 3
   #define VEGETABLE_LATTUCE 4
   #define VEGETABLE_CARROT 5

Also, you define a structure like that:

typedef struct {
   uint32_t id; // the telegram ID of the customer
   uint8_t foodID; // one of the define before
   uint16_t quantity; // the quantity ordered
} foodOrder;

When a customer choose a kind of food, you add a record of foodOrder struct in a array/dinamically allocated list.

For example, if a customer 11735 push the button [Meat] -> [Chicken] then you will add a record with id = 11735 and foodID=MEAT_CHICKEN

If a customer send a text message, the message handler function scan the array/list searching the telegram customer ID. If find it, the message is related to the order found, otherwise is a general text message.

In the example above, if the customer 11735 wrote 500, the message handler function will found a record belonging to 11735 that want a chicken meat so the order can be dispached to the kitchen.

It's not the best solution but could be a begin.

Can we close the issue?

Best wishes and good luck wit your app!

Stefano

**Closed by shurillu** 2018-09-26 13:37 UTC

**Comment by leobel96** [comment] 2018-09-26 14:05
I thought there was a simpler and better solution but I'll do it in this way. Thank you!
