### ISSUE TITLE
mybot.testconnection() OK but mybotSendMessage() NOK (return 0)

### ISSUE THREAD

**Issue by Franck06200** [shurillu/CTBot#17] opened 2019-01-31 21:00 UTC
Hello
I am running NodeMCU 1.0
Arduino IDE
Board 2.4.2
Your last CTBot version (1.2.0) downloaded from Github today.

My Problems : 
1/ myBot.wifiConnect(ssid, pass) is working but does not return any connection information.
2/ myBot.testConnection() is OK
3/ myBot.sendMessage(ChatId, "TEST") is not working (return 0)

I have checked my internet connection. The NodeMcu can reach google (443)
I am able to send me telegram with same token and ChatId via my laptop using the browser (api.telegram.org/......)

Do you have any clue to solve it ?
Why is there any message back after myBot.wifiConnect(ssid, pass) ?

Grazie mille.

Here my program:
#include "CTBot.h" // Need ArduinoJson library 5.13.2 or lesser
#include <ESP8266WiFi.h>
#include <WiFiClientSecure.h>
#include <WiFiClient.h>

WiFiClientSecure client;
CTBot myBot;

String ssid  = "Livebox-04B8";
String pass  = "mySSID";
String token = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
uint32_t ChatId = -111111111;  // changed for security purpose

void setup() {

Serial.begin(9600);
Serial.println("Starting TelegramBot...");
myBot.wifiConnect(ssid, pass);

  // set the telegram bot token
  myBot.setTelegramToken(token);

  // check if all things are ok
  if (myBot.testConnection())
    Serial.println("\nCTBOTtestConnection OK");
  else
    Serial.println("\nCTBOTtestConnection NOK");
}

void loop() {
  Serial.print("Sending a message via CTBot");
  Serial.println(" with bot token " + token);
   Serial.println(myBot.sendMessage(ChatId, "TEST!"));
  delay (30000);
}

**Comment by shurillu** [comment] 2019-02-01 07:51
Hello Franck,
   thansk for using the library. It's a very weird behavior! 
Could you enable the CTBot library debug mode?
To do this: 
+ go to `<your computer>\Documents\Arduino\libraries\CTBot\src`
+ here you can find a file named `CTBot.h`: open it
+ in the very beginning of the file you can find this line: `#define CTBOT_DEBUG_MODE 0 `
+ change the zero with an one and save

Now open your project, recompile and upload and open the Serial monitor. Now you should see a bunch of log messages. Thses messages are useful to know what's happening.

In any case, have you tried some provided examples? Like EchoBot, for example. Same errors?

Stefano

**Comment by shurillu** [comment] 2019-02-05 09:33
Another question: are you trying to send messages to groups and/or channels? In other words, is the `chatID` negative?
If yes, there is a new branch named `Channel-GroupSupport` that fix that issue.
So please take a look to that branch, install it and try it and let me know if your issue is no more.
In that case, I'll merge that branch to the master one and I'll publish a new release with these fixes.

Stefano

**Comment by shurillu** [comment] 2019-02-27 16:37
This issue should be corrected by #18 so I close it. 
Please feel free to reopen it if the issue is still valid.

**Closed by shurillu** 2019-02-27 16:37 UTC

**Comment by marcellodipietro** [comment] 2019-03-14 09:02
Franck06200 the chat id is a negative number
uint32_t ChatId = -111111111; // changed for security purpose
But you have used an unsigned int that change the number to positive

if you use instead 
int64_t
It will work
Ciao
Marcello

**Comment by fathurnov** [comment] 2020-07-31 04:41
Sir @shurillu can I ask you, why sensor reading is become slow when I connect with the CTbot? If I don't use the CTbot the sensor reading is become fast again.

**Comment by fathurnov** [comment] 2020-07-31 04:43
I'm using the 2.0.0 version right now

**Comment by shurillu** [comment] 2020-07-31 12:40
Hello fathurnov,

   everytime you interact with the Telegram Server (`getNewMessage()`, `sendMessage()` methods for example), the library do all the dirty work using the HTTPS protocol -> it is very complex for such small SOC like ESP8266 and ESP32.
So to do that, it require time.
For these reasons, when you use the library and call methods for interact with the Telegram Server, you have to wait a bit.

Cheers,

Stefano
