### ISSUE TITLE
Unable to connect to Telegram server after April 27

### ISSUE THREAD

**Issue by hamster66** [shurillu/CTBot#93] opened 2022-04-28 11:16 UTC
Hi 
After April 27, the library does not connect to the telegram server. The code did not change, everything worked well for several years. (ESP8266)
In debugging I see the following message:

```
--->connect: WiFi connected
--->connect: IP address: 192.168.1.243
--->connect: Unable to connect to Telegram server
--->sendCommand: Header
POST https://api.telegram.org/botxxxxxxxxxxxxx/getMe HTTP/1.1
Host: api.telegram.org
Content-Length: 5
Content-Type: application/json


--->sendCommand: Payload
null

testConnection NOK
--->connect: Unable to connect to Telegram server
--->sendCommand: Header
POST https://api.telegram.org/botxxxxxxxx/getUpdates HTTP/1.1
Host: api.telegram.org
Content-Length: 76
Content-Type: application/json
```

Please, help!!!

**Comment by Araris** [comment] 2022-04-28 11:41
Exactly the same situation from yesterday, myBot.testConnection() returns false.

**Comment by shurillu** [comment] 2022-04-28 11:49
Hello, I'll check ASAP.

Stefano

**Comment by bbird8** [comment] 2022-04-28 15:33
Confirmed. Same issue here.

**Comment by gcardo** [comment] 2022-04-28 16:54
same here

**Comment by shurillu** [comment] 2022-04-29 06:32
Hello to all,
   the issue seem to be related to an "out of date" fingerprint for HTTPS authentication.
This involves only the ESP8266 boards because the ESP32 uses the HTTPS certificate for authentication.
Anyway, I'm drafting a new release very soon with the new fingerprint. Meanwhile here a quick fix:
```
	uint8_t newFingerprint[20]{ 0x07, 0x36, 0x89, 0x3D, 0x0F, 0xCC, 0x8C, 0xF7, 0xD0, 0x19, 0xB7, 0x83, 0x39, 0xC4, 0xD5, 0x15, 0x70, 0x9A, 0xC6, 0x5D };
	myBot.setFingerprint(newFingerprint);
```
Simply add this two lines in the same place where you initialize the bot (after the token assignment is fine).
This should fix the problem.

I tested it with:
- Arduino v. 1.8.15
- ESP32 toolchain v. 2.0.3-RC1
- ArduinoJson v. 6.19.4

Obviously you need to recompile&upload a new firmware with the updated fingerprint.
Please let me know if this fix solve the issue (as I believe).

Cheers
Stefano

**Comment by bbird8** [comment] 2022-04-29 06:53
Yep - I can confirm that the fix works :) 
Thanks!

**Comment by shurillu** [comment] 2022-04-29 07:13
Good! I just drafted the new release (v2.1.9) and updated the v3.0.0 in the his own branch.

Stefano

**Comment by Araris** [comment] 2022-04-29 07:21
Stefano, many thanks to you !

**Comment by dbunshin** [comment] 2022-04-29 07:54
thank you stefano

**Comment by gcardo** [comment] 2022-04-29 08:10
Thanks Stefano!

**Comment by hamster66** [comment] 2022-04-29 11:31
Thank you Stefano! You are best! :)

**Comment by shurillu** [comment] 2022-04-29 17:21
Good: issue solved so I close it.
Feel free to reopen it if something goes wrong.

**Closed by shurillu** 2022-04-29 17:21 UTC

**Comment by DumahBrazorf** [comment] 2022-04-30 11:37
Yeah this should be sticked in the home page. 
Basically every older version than 2.19 won't work anymore with the ESP8266 unless adding the 2lines code trick.
